---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: poc-trigger-gitlab-pipeline
  title: PoC Gitlab Pipeline on Entity
  description: Selects an entity and triggers a Gitlab pipeline for it.
spec:
  owner: roadie
  type: template
  parameters:
    - title: Select project
      properties:
        projectId:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            path: "catalog/entities"
            params:
              filter: "kind=system,metadata.annotations.gitlab.com/project-id"
            valueSelector: "metadata.annotations['gitlab.com/project-id']"
            labelTemplate: '{{item.metadata.name}} ({{item.metadata.annotations["gitlab.com/project-id"]}})'

    - title: Select pipeline type
      properties:
        action:
          title: Action
          type: string
          description: The action to carry out
          enum:
            - ExplodingBarrels
            - StuffingAnimals
          default: ExplodingBarrels

  steps:
    - id: trigger-pipeline
      name: Trigger GitLab Pipeline
      action: http:backstage:request
      input:
        method: POST
        path: '/gitlab/projects/${{ parameters.projectId }}/trigger/pipeline'
        headers:
          Content-Type: 'application/x-www-form-urlencoded'
        body:
          ref: 'roadie.io-poc'
          'variables[TRIGGER]': 'Roadie'
          token: 'glptt-WZsb4ExdtRyyxH6-FjzX'

    - id: output
      name: Output Pipeline URL
      action: debug:log
      input:
        message: "Pipeline triggered! URL: ${{ steps['trigger-pipeline'].output.web_url }}"

  output:
    # The pipelineUrl output is useful for linking back to the created pipeline run
    pipelineUrl: ${{ steps['trigger-pipeline'].output.web_url }}
